---
title: "Reading Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(plotly)
library(networkD3)
library(shiny)
library(textclean)
library(scales)
library(Rcpp)
library(dichromat)
library(plotly)
library(DT)
library(dygraphs)
library(lubridate)
library(reshape2)
library(repmis)
library(readr)
library(googledrive)
```


```{r dataglobal1, include=FALSE}
# Data Twitter Change
id0 <- "1RAalTLYhpprDCpE_wos48ymufN8mjMG_" # twit-mention-change.csv 
id1 <- "11WTedaaE79EtT4vOGNU2vfG7xgcLtJcE" # twit-tagar-balitolakreklamasi.csv
id2 <- "1984jmFur63PmYvoC8Ab6P2iwfUQYVp71" # twit-tagar-balinotforsale.csv

twit_to_change <- read_csv(sprintf("https://docs.google.com/uc?id=%s&export=download", id0))
btr_raw <- read_csv(sprintf("https://docs.google.com/uc?id=%s&export=download", id1))
bns_raw <- read_csv(sprintf("https://docs.google.com/uc?id=%s&export=download", id2))

# gabungan twit change
twit_to_change <- twit_to_change[,-4]
btr_raw <- btr_raw[,-4]
bns_raw <- bns_raw[,-4]

twit_to_change <- twit_to_change %>%
  select(-replying)
btr_raw <- btr_raw %>%
  select(-replying)
bns_raw <- bns_raw %>%
  select(-replying)
twit_change <- bind_rows(twit_to_change, btr_raw, bns_raw)

rm(bns_raw, btr_raw, twit_to_change)
rm(id0, id1, id2)

twit_change <- twit_change %>%
  filter(is_duplicate == "FALSE") %>%
  filter(word_count >= 2)

# Data Petisi Change
# Data Media Change
```


```{r dataglobal2, include=FALSE}
# Data Twitter Gojek
# Data Petisi Gojek
# Data Playstore Gojek
# Data Media Gojek
```



Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

